### ISSUE TITLE
Broken link "Fork me on GitHub"

### ISSUE THREAD

**Issue by inkydragon** [ralexander-phi/which-license#3]
https://github.com/ralexander-phi/which-license/blob/f91d023f370221d9574ebeb96f5a5f99729a05b3/pages/index.tsx#L34

https://alexsci.com/which-license/github.com/ralexander-phi/which-license

```diff
-    <p>Fork me on <a href="github.com/ralexander-phi/which-license">GitHub</a></p>
+    <p>Fork me on <a href="//github.com/ralexander-phi/which-license">GitHub</a></p>
```

**Comment by ralexander-phi** [comment]
Whoops. Thanks!
